### ISSUE TITLE
Image Loading when the internet connection is not available

### ISSUE THREAD

**Issue by kondanta** [Egomination/mangapplizer#3]
When we perform the search, it loads the given image from the network. But when the connection is lost or we don't have in the first place, "or" the image link is broken/invalid it continuously tries to load it and fails. We have to handle this in a way that, if the network connection is not available, there'll be a stock image that indicating the image not available for the users.

**Comment by sasalx** [comment]
Can we use something like failback image or something similar to that? Or maybe we can create a new widget for that.

**Comment by kondanta** [comment]
Sounds reasonable. I'm planning to use https://github.com/jogboms/flutter_offline for checking whether the internet is available.

**Comment by sasalx** [comment]
Side note: Same thing is happening if it can't connect to API too. I think we should give a different error for that.

**Comment by kondanta** [comment]
I put some timeout duration for this. There's no actual solution in current PR but am planning to look at this before beta.

**Comment by sasalx** [comment]
Then, for now, I am putting the future label.
