### ISSUE TITLE
Sticky App Bar on Details Page

### ISSUE THREAD

**Issue by kondanta** [Egomination/mangapplizer#5]
As for the definition, Sticky App Bar is the custom application bar that will change its visibility and content. For the content switch, I am planning to use scrollable's position getter but it is not working for now. Plus, I'll work on this after Alpha first or second. If @sasalx, you want to improve faster, you might consider starting working on now.

Edit:
References:
https://cogitas.net/scroll-position-flutter-listview/
https://stackoverflow.com/questions/54065354/how-to-detect-scroll-position-of-listview-in-flutter
https://medium.com/@diegoveloper/flutter-lets-know-the-scrollcontroller-and-scrollnotification-652b2685a4ac
<https://github.com/flutter/flutter/issues/19941>
https://medium.com/flutter-io/managing-visibility-in-flutter-f558588adefe

**Comment by sasalx** [comment]
For now, we don't have to do that but I believe this idea can enchant the UX.

**Comment by kondanta** [comment]
I am closing this issue since it's become irrelevant regarding the new design I am about the implement.
